### ISSUE TITLE
unsupported parameter value type "TrueClass" in 1.4.2

### ISSUE THREAD

**Issue by abriel** [niwo/cloudstack_client#7]
Hi,

I see that some behavior is changed since 1.4.1.
For example in list_tags, option `listall` with TrueClass value does not work now.
```
        22>>               cloudstack_api.list_tags(
        23:                  resourcetype: 'UserVm', listall: true,
        24:                  key: tag_key, value: tag_value).map { |x| x['resourceid'] }
```

Downgrade to 1.4.1 helps.
But should this happened? Since we have only patch version upgrade.

**Comment by niwo** [comment]
Hi,

Thanks for the hint, this was not intended. I reverted this behavior in 1.4.3.
