### ISSUE TITLE
Release latest version on the RubyGem

### ISSUE THREAD

**Issue by OlegChuev** [niwo/cloudstack_client#9]
Hi there! I hope you're doing great.

Thanks a lot for this wonderful gem and all its functionality!

Would you be able to create a new release on the RubyGem with the latest PR merged into main? I believe it doesn't have the latest changes from main.
[Link to PR](https://github.com/niwo/cloudstack_client/pull/8)

Thanks!

**Comment by niwo** [comment]
@OlegChuev Thanks for the PR, looks good!

**Comment by niwo** [comment]
Finally, sorry for the long wait.
https://rubygems.org/gems/cloudstack_client/versions/1.5.9
